### ISSUE TITLE
Fix student data errors

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#52]
I'm not entirely sure where all this is pulling from these days, so I thought I'd run it to you @bjornmeansbear. 
1. Under Gallery D Center / Hoffberger- "Bryan Hempel" should be Sean Sweeney
2. Sarah Jacoby is exhibiting in Decker (not Meyerhoff)
3. Stacey Montebello is exhibiting in Meyerhoff (not Decker)

**Comment by bjornmeansbear** [comment]
Name errors would be coming from the main student data spreadsheet.
The Gallery errors are probably in LIVEDATA_StudentGalleryPlacement

**Comment by emmasf** [comment]
I fixed point 1 in the student data spreadsheet.

2 and 3 were already correct in the LIVEDATA_StudentGalleryPlacement, but I confirmed that they are wrong on the site.

**Comment by bjornmeansbear** [comment]
Okay.
Then we probably just need to run a data pull...
Whew. Kai and I thought this was gonna be so easy :)

**Comment by emmasf** [comment]
Any word on 
02. Sarah Jacoby is exhibiting in Decker (not Meyerhoff)
03. Stacey Montebello is exhibiting in Meyerhoff (not Decker)
? It looks right to me in the the doc you referenced....

**Comment by bjornmeansbear** [comment]
@emmasf Any other changes that need to be made or pulled in off the top of your head? I'll ask kai to do a new pull either later tonight or first thing tomorrow.

**Comment by emmasf** [comment]
First thing tomorrow would be great, I'll double check when I get out of class.thanks!

Typed on a phone, please excuse brevity.

**Comment by bjornmeansbear** [comment]
@emmasf — So, @webmasterkai did a data pull — the sean sweeney/hempel thing seems to have been fixed. However, those two girls still show up in incorrect galleries because their ID# in the gallery placement Spreadsheet doesn't match their ID# in the student data sheet. 

On the site, the name Sarah Jacoby and  is associated with ID# 434715, this is pulled from the student response form along with her captions, images, etc... but in the gallery placement doc ID#434715 is associated with Joshua Heinsz — this is the same with Montebello, she entered #408939 into the response spreadsheet, but in the gallery spreadsheet #408939 is Valeria Molinari … If the images are correct, then its just some error in this one: https://docs.google.com/spreadsheet/ccc?key=0AvPe_NdeKbxjdFFWU0lpSmJYV3NUSlIzcGU1cWRWTnc&usp=drive_web#gid=0 — Maybe you can ask Morgan to confirm the IDs there as they aren't matching with what the students input themselves?

**Comment by emmasf** [comment]
It was her error, it is now fixed. Thanks!

On Thu, Mar 6, 2014 at 10:50 AM, Kristian Bjørnard <notifications@github.com

**Comment by webmasterkai** [comment]
i pulled the latest data down

**Comment by bjornmeansbear** [comment]
@nourtabet or @emmasf Jacoby is still showing up in Meyerhoff, but it is because she is listed as being in that gallery in the LIVEDATA_StudentGalleryPlacement spreadsheet — so, does that need to be changed to Decker still in the data?

The Montebello & Hempel/Sean Sweeney issues are addressed.

**Comment by emmasf** [comment]
I've asked Grad Studies to proofread this list. They made the original edit
here, and I see that they did not edit Jacoby.

On Tue, Mar 11, 2014 at 3:17 PM, Kristian Bjørnard <notifications@github.com

**Comment by nourtabet** [comment]
we didn't go through all the corrections yet.
NO TIME!#@$%^&*

**Comment by bjornmeansbear** [comment]
I found a lot of small things that I tweaked in regards to peoples statement ¶s that were more apparent now that line returns are showing up. However, do we still need to ask Grad Studies to do a final once through? is there anything else from that collected document of changes that need to be made?

**Comment by nourtabet** [comment]
@bjornmeansbear all the corrections have been made! thanks

**Comment by emmasf** [comment]
Grad studies does want to do a final review.............

Typed on a phone, please excuse brevity.
